@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Creating GitHub Repo...
gh repo create portfolio --public --source=. --remote=origin
echo Pushing to GitHub...
git push -u origin HEAD
echo Configuring Pages...
gh pages set --source "HEAD:/"
echo Done.
